BEGIN {
	l=0;
	p=0;
}
{
	s=$0;
	sub(/^[ \t\r\n]+$/, "", s);
	sub(/[ \t\r\n]+$/, "", s);
	sub(/[ \t\r\n]+/, " ", s);
	if (s~/^\[\!\[\].images\/Spanish_Info.png.\].javascript:\/\/[0-9]+.$/) {
		next;
	}
	if (p==0 && (s~/^\[?\!\[\]/ || (s~/^GENERATED BY: Lectora Online/))) {
		next;
	}
	if (length(s)==0) {
		if (p==0) next;
		l++;
		if (l>1) next;
	} else {
		l=0;
	}
	print s;
	p++;
}
